# ID Mappings File
# Purpose: Defines payee-specific ID extraction and ordering rules for transaction entry.
# Structure: Each payee maps to a prioritized list of identifier orders and optional regex hints.
# See: [add-transactions SKILL.md](./SKILL.md) for usage details and rules.
# KFC: Only use (receipt_id, store_id) for KFC
"大生生活超市 (DS Groceries)":
  orders:
    - [receipt_no]
  regex:
    receipt_no: "\\d{7}"
"KFC":
  orders:
    - [receipt_id, store_id]
  regex:
    receipt_id: "\\d{3}-\\d{3}-\\d{6}"
    store_id: "K\\d{4}"
"快樂小羊火鍋餐廳":
  orders:
    - [receipt_no, table_no]
  regex:
    receipt_no: "\\d{5}/\\d{3}"
    table_no: "B\\d{1,2}"
"沙嗲王 (Satay King)":
  orders:
    - [receipt_id, kiosk_code]
  regex:
    receipt_id: "\\d{5,}\\/\\d{3}"
    kiosk_code: "\\d{1,}"
"McDonald's":
  orders:
    - [machine_txn, order_no, csn]
  regex:
    machine_txn: "[0-9A-Fa-f]{6}\\\\/\\\\d{1,5}"
    order_no: "\\d{1,5}"
    csn: "\\d{1,3}"
"Cafe 100%":
  orders:
    - [transaction_id, table_number]
  regex:
    transaction_id: "\\d{6,}"
    table_number: "\\d{1,3}"
"Saizeriya":
  orders:
    - [transaction_id, bill_number, table_number]
  regex:
    transaction_id: "[0-9A-Z]{10,}"
    bill_number: "\\d{3}-\\d{6}"
    table_number: "\\d+"
# Taste: Use (transaction_id, terminal_id) in this order. transaction_id is the 22-character alphanumeric code (e.g., 5B10612602021353394C18), terminal_id is the 22-digit numeric code (e.g., 8747640135330320260202). Only these two should be included in the payee line, in this order.
"Taste":
  orders:
    - [transaction_id, terminal_id]
  regex:
    transaction_id: "[0-9A-Z]{22}"
    terminal_id: "\\d{22}"
"天仁茗茶 (TenRen's Tea)":
  orders:
    - [transaction_id]
  regex:
    transaction_id: "[A-Z0-9\\-]{16,32}"
"AC2 Canteen, CityUHK":
  orders:
    - [transaction_id, receipt_id, terminal_id]
  regex:
    transaction_id: "[0-9A-Z]{20,}"
    receipt_id: "\\d{9}"
    terminal_id: "\\d+"
"風味園":
  orders:
    - [cardno, table_number]
  regex:
    cardno: "\\d{6,}"
    table_number: "\\d+"
"城大食坊 (City Express)":
  orders:
    - [transaction_id]
  regex:
    transaction_id: "\\d{10,}"
"ad982faf-117f-4ddc-bc68-3606fb71ff52":
  orders:
    - [transaction_id, register_id, table_number]
  regex:
    transaction_id: "\\d{8}"
    register_id: "\\d{4}"
    table_number: "\\d+"
"Natong Thai Restaurant":
  orders:
    - [order_no, table_no]
  regex:
    order_no: "OrdNo\\.\\s*(\\d+)"
    table_no: "^(\\d{2})$"
"Wonderland Superstore":
  orders:
    - [receipt_id]
  regex:
    receipt_id: "\\d{7}"
