# Payee Mappings File
# Purpose: Maps payee aliases and translations to canonical payee names for use in transaction entry.
# Structure: Each entry maps a source/alias to a canonical form. Do not include identity mappings or ambiguous tokens.
# See: [add-transactions SKILL.md](./SKILL.md) for usage details and rules.
"沙嗲王": "沙嗲王 (Satay King)"
"McDonald's Hong Kong": "McDonald's"
"百份百": "Cafe 100%"
"錦麗": "錦麗 (Phole)"
"天仁茗茶": "天仁茗茶 (TenRen's Tea)"
"大生生活超市": "大生生活超市 (DS Groceries)"
